// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7claNE9kFJE2LN3P-o82Au-tk03HIYGM',
    appId: '1:1059819211045:web:4221eb712354079222b2cc',
    messagingSenderId: '1059819211045',
    projectId: 'acg-app-c07d9',
    authDomain: 'acg-app-c07d9.firebaseapp.com',
    storageBucket: 'acg-app-c07d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXd-9DnBMMLzzDbWosmEJbuG2nHQA1gxA',
    appId: '1:1059819211045:android:72dcccf0cabb3fe622b2cc',
    messagingSenderId: '1059819211045',
    projectId: 'acg-app-c07d9',
    storageBucket: 'acg-app-c07d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc2vS2gfJ86ORmgu6DePIjRy4HT7tPksI',
    appId: '1:1059819211045:ios:8b25f7010dbf388822b2cc',
    messagingSenderId: '1059819211045',
    projectId: 'acg-app-c07d9',
    storageBucket: 'acg-app-c07d9.appspot.com',
    iosBundleId: 'com.example.sOs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc2vS2gfJ86ORmgu6DePIjRy4HT7tPksI',
    appId: '1:1059819211045:ios:8b25f7010dbf388822b2cc',
    messagingSenderId: '1059819211045',
    projectId: 'acg-app-c07d9',
    storageBucket: 'acg-app-c07d9.appspot.com',
    iosBundleId: 'com.example.sOs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7claNE9kFJE2LN3P-o82Au-tk03HIYGM',
    appId: '1:1059819211045:web:d9457a6f0a9d00b522b2cc',
    messagingSenderId: '1059819211045',
    projectId: 'acg-app-c07d9',
    authDomain: 'acg-app-c07d9.firebaseapp.com',
    storageBucket: 'acg-app-c07d9.appspot.com',
  );
}
